from google import genai
import pandas as pd
import json
import os
import asyncio
from dotenv import load_dotenv
from tqdm import tqdm


INPUT_FILE = "/Unbias/VLDBench_5k_60_40_balanced.csv"
ENV_PATH = "/secret_keys/.env"
BASE_OUTPUT_DIR = "/Unbias"

CHECKPOINT_DIR = os.path.join(BASE_OUTPUT_DIR, "checkpoints_gpt")
CHECKPOINT_FILE = os.path.join(CHECKPOINT_DIR, "checkpoint.json")
FINAL_OUTPUT_FILE = os.path.join(BASE_OUTPUT_DIR, "Unbias-plus-dataset.json")

TEMPERATURE = 0.2
MAX_RETRIES = 3
MAX_CONCURRENT_REQUESTS = 10

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

load_dotenv(ENV_PATH)
API_KEY = os.getenv("GEMINI_API_KEY")

if API_KEY is None:
    raise ValueError("GEMINI_API_KEY not found")

client = genai.Client(api_key=API_KEY)

df = pd.read_csv(INPUT_FILE)
total_rows = len(df)
print("Total rows:", total_rows)

if os.path.exists(CHECKPOINT_FILE):
    with open(CHECKPOINT_FILE, "r", encoding="utf-8") as f:
        results = json.load(f)

    if len(results) > 0:
        last_saved_index = max(r["index"] for r in results)
        start_index = last_saved_index + 1
        print(f"Resuming from index {start_index}")
    else:
        start_index = 0
else:
    results = []
    start_index = 0
    print("Starting fresh.")

results_lock = asyncio.Lock()


schema = {
    "type": "object",
    "properties": {
        "severity": {"type": "integer", "minimum": 2, "maximum": 4},
        "bias_found": {"type": "boolean"},
        "unbiased_text": {"type": "string"},
        "biased_segments": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "original": {"type": "string"},
                    "replacement": {"type": "string"},
                    "severity": {
                        "type": "string",
                        "enum": ["high", "medium", "low"]
                    },
                    "bias_type": {"type": "string"},
                    "reasoning": {"type": "string"}
                },
                "required": [
                    "original",
                    "replacement",
                    "severity",
                    "bias_type",
                    "reasoning"
                ]
            }
        }
    },
    "required": ["severity", "bias_found", "unbiased_text", "biased_segments"]
}


def build_prompt_biased_only(article_text):

    return f"""
You are an expert linguist and bias detection specialist.

Your task:
1. Identify ALL biased, loaded, or prejudiced language in the text.
2. For each biased segment, propose a neutral replacement.
3. Generate a fully neutral version of the text using those replacements.
This article is labeled as BIASED (supervised label).
Global severity MUST be 2, 3, or 4.

-----------------------------------------
BIAS TYPES TO DETECT
-----------------------------------------
- Loaded language
- Dehumanizing framing
- False generalizations
- Framing bias
- Euphemisms or dysphemisms
- Politically charged terminology
- Sensationalism

-----------------------------------------
GLOBAL SEVERITY SCALE (2–4)
-----------------------------------------
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

-----------------------------------------
SEGMENT SEVERITY
-----------------------------------------
- high: dehumanizing or strongly prejudiced
- medium: framing bias or loaded terms
- low: subtle bias

-----------------------------------------
SEGMENT RULES
-----------------------------------------
- A segment is a consecutive sequence of words forming one biased idea.
- Adjacent biased words = ONE segment.
- Separated biased words = separate segments.
- "original" MUST be the EXACT substring from input (case-sensitive).
- Do NOT paraphrase the original field.

-----------------------------------------
OUTPUT FORMAT
-----------------------------------------
Return ONLY a valid JSON object (no markdown, no explanation outside JSON):

{{
  "severity": 2 | 3 | 4,
  "bias_found": true,
  "unbiased_text": "The rewritten, neutral version of the full text",
  "biased_segments": [
    {{
      "original": "exact substring from input text",
      "replacement": "neutral alternative phrase",
      "severity": "high" | "medium" | "low",
      "bias_type": "brief label (e.g., loaded language / framing bias)",
      "reasoning": "1-2 sentence explanation"
    }}
  ]
}}

If multiple biased segments exist, return multiple objects.

-----------------------------------------
UNBIASED TEXT CONSTRUCTION RULES
-----------------------------------------
- The "unbiased_text" must preserve all factual information.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

-----------------------------------------
ARTICLE
-----------------------------------------
\"\"\"{article_text}\"\"\"
"""

async def save_checkpoint():
    async with results_lock:
        ordered = sorted(results, key=lambda x: x["index"])
        with open(CHECKPOINT_FILE, "w", encoding="utf-8") as f:
            json.dump(ordered, f, indent=2, ensure_ascii=False)
        print("Checkpoint saved.")

async def process_row(idx, semaphore):

    async with semaphore:

        row = df.iloc[idx]
        article = row["article_text"]
        binary_label = row["classification_label"]

        if binary_label == "unbiased":
            result_entry = {
                "index": idx,
                "binary_label": binary_label,
                "article_text": article,
                "severity": 0,
                "bias_found": False,
                "biased_segments": [],
                "unbiased_text": article
            }

        else:
            retries = 0
            parsed = None

            while retries < MAX_RETRIES:
                try:
                    loop = asyncio.get_running_loop()

                    response = await loop.run_in_executor(
                        None,
                        lambda: client.models.generate_content(
                            model="gemini-3-flash-preview",
                            contents=build_prompt_biased_only(article),
                            config={
                                "temperature": TEMPERATURE,
                                "response_mime_type": "application/json",
                                "response_schema": schema
                            }
                        )
                    )

                    parsed = response.parsed
                    if parsed is not None:
                        break

                except Exception as e:
                    print(f"Retry {retries+1} failed at index {idx}: {e}")

                retries += 1
                await asyncio.sleep(2)

            if parsed is None:
                print(f"Skipping index {idx}")
                return

            severity = parsed.get("severity", 2)
            if not isinstance(severity, int):
                severity = 2
            parsed["severity"] = max(2, min(4, severity))

            validated_segments = []

            for seg in parsed.get("biased_segments", []):
                if (
                    isinstance(seg, dict)
                    and isinstance(seg.get("original"), str)
                    and seg["original"] in article
                ):
                    validated_segments.append(seg)

            parsed["biased_segments"] = validated_segments
            parsed["bias_found"] = True

            result_entry = {
                "index": idx,
                "binary_label": binary_label,
                "article_text": article,
                "severity": parsed["severity"],
                "bias_found": parsed["bias_found"],
                "biased_segments": parsed["biased_segments"],
                "unbiased_text": parsed.get("unbiased_text")
            }

        async with results_lock:
            results.append(result_entry)


async def main():

    global results  # make intent explicit (safe + clean)

    semaphore = asyncio.Semaphore(MAX_CONCURRENT_REQUESTS)

    batch_size = MAX_CONCURRENT_REQUESTS
    indices = list(range(start_index, total_rows))

    for i in tqdm(range(0, len(indices), batch_size),
                  desc="Processing VLDBench"):

        batch_indices = indices[i:i + batch_size]

        tasks = [
            process_row(idx, semaphore)
            for idx in batch_indices
        ]

        await asyncio.gather(*tasks)

        # Save checkpoint after each batch
        await save_checkpoint()

    # Final save
    ordered_results = sorted(results, key=lambda x: x["index"])

    # Reassign clean sequential indices
    for new_idx, row in enumerate(ordered_results):
        row["index"] = new_idx

    with open(FINAL_OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered_results, f, indent=2, ensure_ascii=False)

    print("\nFinal results saved with corrected indices.")
    print(f"Total samples: {len(ordered_results)}")

if __name__ == "__main__":
    asyncio.run(main())