"""Asynchronous Gemini-based data generation pipeline for VLDBench."""

import asyncio
import json
import os
from typing import Any, Dict, List

import pandas as pd
from dotenv import load_dotenv
from google import genai
from tqdm import tqdm


INPUT_FILE = "/Unbias/VLDBench_5k_60_40_balanced.csv"
ENV_PATH = "/secret_keys/.env"
BASE_OUTPUT_DIR = "/Unbias"

CHECKPOINT_DIR = os.path.join(BASE_OUTPUT_DIR, "checkpoints_gpt")
CHECKPOINT_FILE = os.path.join(CHECKPOINT_DIR, "checkpoint.json")
FINAL_OUTPUT_FILE = os.path.join(BASE_OUTPUT_DIR, "Unbias-plus-dataset.json")

TEMPERATURE = 0.2
MAX_RETRIES = 3
MAX_CONCURRENT_REQUESTS = 10


schema: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "severity": {"type": "integer", "minimum": 2, "maximum": 4},
        "bias_found": {"type": "boolean"},
        "unbiased_text": {"type": "string"},
        "biased_segments": {"type": "array"},
    },
    "required": ["severity", "bias_found", "unbiased_text", "biased_segments"],
}


def build_prompt_biased_only(article_text: str) -> str:
    """Build Gemini prompt for biased text rewriting."""
    return f"""
You are an expert linguist and bias detection specialist.

Your task:
1. Identify ALL biased, loaded, or prejudiced language in the text.
2. For each biased segment, propose a neutral replacement.
3. Generate a fully neutral version of the text using those replacements.
This article is labeled as BIASED (supervised label).
Global severity MUST be 2, 3, or 4.

-----------------------------------------
BIAS TYPES TO DETECT
-----------------------------------------
- Loaded language
- Dehumanizing framing
- False generalizations
- Framing bias
- Euphemisms or dysphemisms
- Politically charged terminology
- Sensationalism

-----------------------------------------
GLOBAL SEVERITY SCALE (2–4)
-----------------------------------------
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

-----------------------------------------
SEGMENT SEVERITY
-----------------------------------------
- high: dehumanizing or strongly prejudiced
- medium: framing bias or loaded terms
- low: subtle bias

-----------------------------------------
SEGMENT RULES
-----------------------------------------
- A segment is a consecutive sequence of words forming one biased idea.
- Adjacent biased words = ONE segment.
- Separated biased words = separate segments.
- "original" MUST be the EXACT substring from input (case-sensitive).
- Do NOT paraphrase the original field.

-----------------------------------------
OUTPUT FORMAT
-----------------------------------------
Return ONLY a valid JSON object (no markdown, no explanation outside JSON):

{{
  "severity": 2 | 3 | 4,
  "bias_found": true,
  "unbiased_text": "The rewritten, neutral version of the full text",
  "biased_segments": [
    {{
      "original": "exact substring from input text",
      "replacement": "neutral alternative phrase",
      "severity": "high" | "medium" | "low",
      "bias_type": "brief label (e.g., loaded language / framing bias)",
      "reasoning": "1-2 sentence explanation"
    }}
  ]
}}

If multiple biased segments exist, return multiple objects.

-----------------------------------------
UNBIASED TEXT CONSTRUCTION RULES
-----------------------------------------
- The "unbiased_text" must preserve all factual information.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

-----------------------------------------
ARTICLE
-----------------------------------------
\"\"\"{article_text}\"\"\"
"""


async def save_checkpoint(
    results: List[Dict[str, Any]],
    results_lock: asyncio.Lock,
) -> None:
    """Save intermediate results to checkpoint file."""
    async with results_lock:
        ordered = sorted(results, key=lambda x: x["index"])
        with open(CHECKPOINT_FILE, "w", encoding="utf-8") as f:
            json.dump(ordered, f, indent=2, ensure_ascii=False)


async def process_row(
    idx: int,
    df: pd.DataFrame,
    client: genai.Client,
    semaphore: asyncio.Semaphore,
    results: List[Dict[str, Any]],
    results_lock: asyncio.Lock,
) -> None:
    """Process a single dataset row asynchronously."""
    async with semaphore:
        row = df.iloc[idx]
        article = row["article_text"]
        binary_label = row["classification_label"]

        if binary_label == "unbiased":
            result_entry = {
                "index": idx,
                "binary_label": binary_label,
                "article_text": article,
                "severity": 0,
                "bias_found": False,
                "biased_segments": [],
                "unbiased_text": article,
            }
        else:
            parsed = await generate_with_retries(article, client, idx)
            if parsed is None:
                return

            result_entry = {
                "index": idx,
                "binary_label": binary_label,
                "article_text": article,
                "severity": parsed["severity"],
                "bias_found": True,
                "biased_segments": parsed["biased_segments"],
                "unbiased_text": parsed.get("unbiased_text"),
            }

        async with results_lock:
            results.append(result_entry)


async def generate_with_retries(
    article: str,
    client: genai.Client,
    idx: int,
) -> Dict[str, Any] | None:
    """Call Gemini with retry logic and validate output."""
    retries = 0
    while retries < MAX_RETRIES:
        try:
            loop = asyncio.get_running_loop()
            response = await loop.run_in_executor(
                None,
                lambda: client.models.generate_content(
                    model="gemini-3-flash-preview",
                    contents=build_prompt_biased_only(article),
                    config={
                        "temperature": TEMPERATURE,
                        "response_mime_type": "application/json",
                        "response_schema": schema,
                    },
                ),
            )
            parsed = response.parsed
            if not isinstance(parsed, dict):
                retries += 1
                await asyncio.sleep(2)
                continue

            severity = int(parsed.get("severity", 2))
            parsed["severity"] = max(2, min(4, severity))

            return parsed
        except Exception as exc:
            print(f"Retry {retries + 1} failed at index {idx}: {exc}")

        retries += 1
        await asyncio.sleep(2)

    print(f"Skipping index {idx}")
    return None


async def main() -> None:
    """Run full asynchronous data generation pipeline."""
    os.makedirs(CHECKPOINT_DIR, exist_ok=True)

    load_dotenv(ENV_PATH)
    api_key = os.getenv("GEMINI_API_KEY")
    if api_key is None:
        raise ValueError("GEMINI_API_KEY not found")

    client = genai.Client(api_key=api_key)

    df = pd.read_csv(INPUT_FILE)
    total_rows = len(df)
    print("Total rows:", total_rows)

    results: List[Dict[str, Any]] = []
    results_lock = asyncio.Lock()

    semaphore = asyncio.Semaphore(MAX_CONCURRENT_REQUESTS)

    indices = list(range(total_rows))

    for start in tqdm(
        range(0, len(indices), MAX_CONCURRENT_REQUESTS),
        desc="Processing VLDBench",
    ):
        batch = indices[start : start + MAX_CONCURRENT_REQUESTS]
        tasks = [
            process_row(
                idx,
                df,
                client,
                semaphore,
                results,
                results_lock,
            )
            for idx in batch
        ]
        await asyncio.gather(*tasks)
        await save_checkpoint(results, results_lock)

    ordered = sorted(results, key=lambda x: x["index"])

    with open(FINAL_OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)

    print("Final dataset saved.")


if __name__ == "__main__":
    asyncio.run(main())
