"""Evaluate base and fine-tuned bias-rewrite models using an LLM judge.

This script:
- Runs structured JSON inference (via Outlines) for a base model and a fine-tuned model.
- Uses an OpenAI judge model to score each rewrite on
  bias reduction, faithfulness, and fluency.
- Saves per-sample scores and summary statistics to CSV.

Notes
-----
- No heavyweight work executes at import time (pre-commit/doctest friendly).
- Main logic is split into helpers to satisfy Ruff complexity limits.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Literal, Tuple, cast

import outlines
import pandas as pd
import torch
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer


BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"
FT_MODEL = "/Unbias/Models/Qwen25_Unbias_4k_5epoch"

TEST_CSV = "/Unbias/VLDBench_test_50_biased.csv"

MAX_SEQ_LENGTH = 8192
MAX_ARTICLE_TOKENS = 5000

ENV_PATH = "/secret_keys/.env"
OUTPUT_RESULTS = "model_comparison_results_final.csv"

JUDGE_MODEL = "gpt-4o"
JUDGE_TEMPERATURE = 0


SYSTEM_PROMPT = """
You are an expert linguist and bias detection specialist. Your job is to:
1. Identify ALL biased, loaded, or prejudiced language in the given text.
2. Rewrite the text in a neutral, factual, unbiased way.
3. The "unbiased_text" MUST reproduce the entire original article from beginning to end by replacing only the biased segments with their neutral alternatives. No other content may be removed, added, or omitted.
4. For each biased segment, explain why it is biased and how severe it is.
NOTE: All input articles are known to contain biased or loaded language. Your task is to find and correct them fully.

## Global Severity level
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

## BIAS TYPES TO DETECT
- **Loaded language**: Words that carry strong emotional connotations (e.g. "flooding", "invasion", "destroying")
- **Dehumanizing framing**: Language that strips dignity from groups of people
- **False generalizations**: Sweeping statements about groups ("they always", "all of them")
- **Framing bias**: Selective word choices that imply a particular viewpoint
- **Euphemisms or dysphemisms**: Softening or hardening language to manipulate perception
- **Politically charged terminology**: Labels used to provoke rather than describe
- **Sensationalism**: Exaggerated language to evoke emotional responses

## SEVERITY SCALE
- **high**: Dehumanizing, hateful, or strongly prejudiced language
- **medium**: Framing bias, loaded terms, misleading generalizations
- **low**: Subtle word choice bias, mild framing issues

## SEGMENT RULES
- A segment is a consecutive sequence of words that form a single biased idea
- If two biased words are adjacent and part of the same biased idea, treat them as ONE segment
- If biased words are separated by neutral words, treat them as SEPARATE segments
- The "original" field must be the EXACT substring as it appears in the input text (case-sensitive, no changes)

## UNBIASED TEXT CONSTRUCTION RULES
- The "unbiased_text" must preserve all factual information.
- Preserve all facts while neutralizing all biased language.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- The length of "unbiased_text" must be approximately equal to the length of the input article.
- You must rewrite the full article, not only the sentences containing biased segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

Meaning Preservation Rule (Mandatory)
- The rewritten article must preserve the exact original meaning.
- You MUST NOT change facts, timelines, certainty levels, scope of claims, or the subject of any sentence.
- Do not reverse polarity, generalize specific groups (e.g., “children” → “users”), remove qualifiers (e.g., “reportedly”, “according to”), or introduce new claims.
- If a neutral replacement would alter meaning, do not modify that segment.

Structural Integrity Rule (Mandatory)
- The "unbiased_text" must reproduce the entire original article in the same order and structure, modifying only the identified biased segments.
- Do not remove, add, merge, truncate, duplicate, or reformat content.
- Ensure all replacements are grammatically correct and preserve original punctuation and quotations.

Return ONLY valid JSON following the required schema. No extra text.
""".strip()


BiasType = Literal[
    "loaded language",
    "dehumanizing framing",
    "false generalizations",
    "framing bias",
    "euphemism/dysphemism",
    "politically charged terminology",
    "sensationalism",
]
SegmentSeverity = Literal["high", "medium", "low"]
GlobalSeverity = Literal[2, 3, 4]


class BiasedSegment(BaseModel):
    """Represent a single biased segment detected in the input article."""

    original: str = Field(
        ..., description="Exact case-sensitive substring from input text"
    )
    replacement: str = Field(..., description="Neutral alternative phrase")
    severity: SegmentSeverity
    bias_type: BiasType
    reasoning: str = Field(..., description="1-2 sentence explanation")


class BiasOutput(BaseModel):
    """Represent structured bias detection output including full neutral rewrite."""

    severity: GlobalSeverity
    biased_segments: List[BiasedSegment]
    unbiased_text: str


@dataclass(frozen=True)
class InferenceResult:
    """Store normalized inference results for downstream evaluation."""

    unbiased_text: str
    severity: int
    biased_segments: List[Dict[str, Any]]


def build_prompt(article_text: str) -> str:
    """Build a single prompt string embedding system instructions and the article."""
    return f"""SYSTEM:
{SYSTEM_PROMPT}

USER:
Analyze the following article and return JSON only.

ARTICLE:
\"\"\"{article_text}\"\"\"
"""


def get_token_length(tokenizer: Any, text: str) -> int:
    """Return the token length of text using the provided tokenizer."""
    return len(tokenizer.encode(text, add_special_tokens=False))


def post_validate_and_fix(article_text: str, parsed: Dict[str, Any]) -> Dict[str, Any]:
    """Filter segments whose `original` is not in the article."""
    segs = parsed.get("biased_segments", [])
    filtered: List[Dict[str, Any]] = []

    for seg in segs:
        orig = seg.get("original", "")
        if isinstance(orig, str) and orig and orig in article_text:
            filtered.append(seg)

    parsed["biased_segments"] = filtered
    return parsed


def load_outlines_model(model_path: str) -> Tuple[Any, Any]:
    """Load a CausalLM and wrap it with Outlines."""
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    hf_model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    hf_model.eval()

    outlines_model = outlines.from_transformers(hf_model, tokenizer)
    return outlines_model, tokenizer


def compute_max_new_tokens(
    tokenizer: Any,
    prompt: str,
    model_limit: int = 32768,
    buffer: int = 500,
    hard_cap: int = 15000,
) -> int:
    """Compute a safe dynamic generation budget based on prompt token length."""
    input_tokens = len(tokenizer.encode(prompt, add_special_tokens=False))
    available = model_limit - input_tokens - buffer
    if available <= 0:
        raise ValueError("Prompt too long for model context window.")
    return min(hard_cap, available)


def run_inference(
    outlines_model: Any,
    tokenizer: Any,
    article_text: str,
) -> InferenceResult:
    """Run schema-constrained inference with dynamic token budgeting and validation."""
    prompt = build_prompt(article_text)

    max_new = compute_max_new_tokens(tokenizer, prompt)

    json_text = outlines_model(
        prompt,
        BiasOutput,
        max_new_tokens=max_new,
    )

    if not json_text.strip().endswith("}"):
        # Retry with a conservative cap based on article size
        article_tokens = len(tokenizer.encode(article_text, add_special_tokens=False))
        capped_max = min(int(article_tokens * 2), 12000)

        json_text = outlines_model(
            prompt,
            BiasOutput,
            max_new_tokens=capped_max,
        )

        if not json_text.strip().endswith("}"):
            raise ValueError("Model output truncated after retry.")

    obj = BiasOutput.model_validate_json(json_text).model_dump()
    obj = post_validate_and_fix(article_text, obj)

    return InferenceResult(
        unbiased_text=obj["unbiased_text"],
        severity=int(obj["severity"]),
        biased_segments=list(obj["biased_segments"]),
    )


def create_judge_client() -> OpenAI:
    """Create and return an OpenAI client using API key from ENV_PATH."""
    load_dotenv(ENV_PATH)
    api_key = os.getenv("OPENAI_API_KEY")
    if api_key is None:
        raise ValueError("OPENAI_API_KEY not found in .env file")
    return OpenAI(api_key=api_key)


def validate_judge_output(obj: Dict[str, Any]) -> None:
    """Validate that judge JSON contains required structure and score ranges."""
    if "A" not in obj or "B" not in obj:
        raise ValueError("Judge output missing A or B")

    for key in ("A", "B"):
        if key not in obj or not isinstance(obj[key], dict):
            raise ValueError(f"Judge output missing object for {key}")
        for metric in ("bias", "faithfulness", "fluency"):
            if metric not in obj[key]:
                raise ValueError(f"Missing {metric} in judge output")
            if not isinstance(obj[key][metric], int):
                raise ValueError(f"{metric} must be integer")
            if not (0 <= obj[key][metric] <= 5):
                raise ValueError(f"{metric} must be 0-5")


def build_judge_prompt(original: str, rewrite_a: str, rewrite_b: str) -> str:
    """Build the evaluation prompt for scoring two rewrites."""
    return f"""
You are an expert evaluator of political bias correction in news text.

Your task is to evaluate two rewritten versions of an original article.
The original article is known to be biased. Your goal is to assess how well each rewrite neutralizes the bias while preserving the original meaning.
------------------------------------------
ORIGINAL ARTICLE:
------------------------------------------
{original}

------------------------------------------
REWRITE A:
------------------------------------------
{rewrite_a}

------------------------------------------
REWRITE B:
------------------------------------------
{rewrite_b}

------------------------------------------
EVALUATION INSTRUCTIONS
------------------------------------------

You must evaluate each rewrite independently using the following criteria:

1. Bias Reduction (0–5)
- 0 = Highly biased language remains
- 1 = Minimal bias reduction
- 2 = Some bias reduced but framing still persuasive
- 3 = Moderately neutral but subtle bias remains
- 4 = Largely neutral with minimal residual framing
- 5 = Fully neutral, factual, and free of emotionally loaded language

2. Faithfulness to Original Facts (0–5)
- 0 = Major factual distortions or added information
- 1 = Multiple factual inaccuracies
- 2 = Some meaning distortion
- 3 = Mostly faithful with minor paraphrasing drift
- 4 = Faithful to original facts with neutral wording
- 5 = Completely faithful, no factual changes

Important:
- Do NOT penalize for shortening text.
- Do penalize if new claims are introduced.
- Do penalize if key factual claims are removed.

3. Fluency & Coherence (0–5)
- 0 = Unreadable or broken grammar
- 1 = Major grammatical issues
- 2 = Understandable but awkward
- 3 = Mostly fluent with minor issues
- 4 = Fluent and well-structured
- 5 = Highly fluent and professional

------------------------------------------
SCORING RULES
------------------------------------------

- Scores must be integers only.
- Scores must be between 0 and 5.
- Evaluate A and B independently.
- Return ONLY valid JSON.
- Do NOT include commentary.

------------------------------------------
OUTPUT FORMAT
------------------------------------------

{{
  "A": {{"bias": int, "faithfulness": int, "fluency": int}},
  "B": {{"bias": int, "faithfulness": int, "fluency": int}}
}}
""".strip()


def judge_models(
    judge_client: OpenAI,
    original: str,
    rewrite_a: str,
    rewrite_b: str,
) -> Dict[str, Any]:
    """Score two rewrites using an OpenAI judge model."""
    prompt = build_judge_prompt(original, rewrite_a, rewrite_b)

    response = judge_client.chat.completions.create(
        model=JUDGE_MODEL,
        temperature=JUDGE_TEMPERATURE,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.choices[0].message.content or ""
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("Judge did not return JSON")

    parsed = cast(Dict[str, Any], json.loads(raw[start : end + 1]))
    validate_judge_output(parsed)
    return parsed


def load_test_dataframe() -> pd.DataFrame:
    """Load the test dataset as a DataFrame."""
    return pd.read_csv(TEST_CSV)


def filter_by_article_tokens(
    df: pd.DataFrame,
    tokenizer: Any,
    max_article_tokens: int,
) -> pd.DataFrame:
    """Filter dataset rows to those under a maximum article token length."""
    token_lengths: List[int] = []
    keep_mask: List[bool] = []

    for _, row in df.iterrows():
        article = row["article_text"]
        token_len = get_token_length(tokenizer, article)
        token_lengths.append(token_len)
        keep_mask.append(token_len <= max_article_tokens)

    df = df.copy()
    df["token_length"] = token_lengths
    return df[keep_mask].reset_index(drop=True)


def append_result_row(
    results: List[Dict[str, Any]],
    idx: int,
    scores: Dict[str, Any],
) -> None:
    """Append a single scoring result row to the results list."""
    results.append(
        {
            "index": idx,
            "base_bias": scores["A"]["bias"],
            "base_faithfulness": scores["A"]["faithfulness"],
            "base_fluency": scores["A"]["fluency"],
            "ft_bias": scores["B"]["bias"],
            "ft_faithfulness": scores["B"]["faithfulness"],
            "ft_fluency": scores["B"]["fluency"],
        }
    )


def safe_write_results_csv(results: List[Dict[str, Any]], path: str) -> None:
    """Write current results to CSV."""
    pd.DataFrame(results).to_csv(path, index=False)


def summarize_results(results_df: pd.DataFrame) -> None:
    """Print aggregate averages and win-rate summary for the evaluation."""
    if len(results_df) == 0:
        print("No successful samples to summarize.")
        return

    print("\nBASE MODEL AVERAGES:")
    print(results_df[["base_bias", "base_faithfulness", "base_fluency"]].mean())

    print("\nFINE-TUNED MODEL AVERAGES:")
    print(results_df[["ft_bias", "ft_faithfulness", "ft_fluency"]].mean())

    results_df = results_df.copy()
    results_df["base_total"] = (
        results_df["base_bias"]
        + results_df["base_faithfulness"]
        + results_df["base_fluency"]
    )
    results_df["ft_total"] = (
        results_df["ft_bias"] + results_df["ft_faithfulness"] + results_df["ft_fluency"]
    )

    ft_wins = int((results_df["ft_total"] > results_df["base_total"]).sum())
    base_wins = int((results_df["base_total"] > results_df["ft_total"]).sum())
    ties = int((results_df["ft_total"] == results_df["base_total"]).sum())

    print("\nWIN RATE:")
    print(f"FT Wins: {ft_wins}")
    print(f"Base Wins: {base_wins}")
    print(f"Ties: {ties}")


def evaluate_one_article(
    article: str,
    base_model: Any,
    base_tokenizer: Any,
    ft_model: Any,
    ft_tokenizer: Any,
    judge_client: OpenAI,
) -> Dict[str, Any]:
    """Run base/ft inference and judge scoring for a single article."""
    base_out = run_inference(base_model, base_tokenizer, article)
    ft_out = run_inference(ft_model, ft_tokenizer, article)

    return judge_models(
        judge_client,
        original=article,
        rewrite_a=base_out.unbiased_text,
        rewrite_b=ft_out.unbiased_text,
    )


def main() -> None:
    """Run the full base-vs-ft evaluation and save results to CSV."""
    print("Evaluation of 4k 5-epoch trained model")

    judge_client = create_judge_client()

    print("Loading test dataset...")
    df = load_test_dataframe()

    print("Loading base model (Outlines)...")
    base_model, base_tokenizer = load_outlines_model(BASE_MODEL)

    print(f"Filtering articles with token length <= {MAX_ARTICLE_TOKENS}...")
    original_count = len(df)
    df = filter_by_article_tokens(df, base_tokenizer, MAX_ARTICLE_TOKENS)
    print(f"Original samples: {original_count}")
    print(f"Filtered samples: {len(df)}")
    print(f"Removed samples: {original_count - len(df)}")

    print("Loading fine-tuned model (Outlines)...")
    ft_model, ft_tokenizer = load_outlines_model(FT_MODEL)

    results: List[Dict[str, Any]] = []

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        article = row["article_text"]

        try:
            scores = evaluate_one_article(
                article=article,
                base_model=base_model,
                base_tokenizer=base_tokenizer,
                ft_model=ft_model,
                ft_tokenizer=ft_tokenizer,
                judge_client=judge_client,
            )
            append_result_row(results, idx=idx, scores=scores)
            safe_write_results_csv(results, OUTPUT_RESULTS)
        except Exception as exc:
            print(f"ERROR at index {idx}: {exc}")
            continue

    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_RESULTS, index=False)

    print("\n" + "=" * 80)
    print("EVALUATION COMPLETE")
    print("=" * 80)

    summarize_results(results_df)


if __name__ == "__main__":
    main()
