import os
import json
import torch
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from transformers import AutoTokenizer, AutoModelForCausalLM
from openai import OpenAI

import outlines
from typing import List, Literal
from pydantic import BaseModel, Field

print("evaluation of 4k 5 epoch trained model")

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"
FT_MODEL = "/Unbias/Models/Qwen25_Unbias_4k_5epoch"

TEST_CSV = "/Unbias/VLDBench_test_50_biased.csv"

MAX_SEQ_LENGTH = 8192          
MAX_NEW_TOKENS = 8000          
MAX_ARTICLE_TOKENS = 5000

ENV_PATH = "/secret_keys/.env"
OUTPUT_RESULTS = "model_comparison_results_final.csv"

load_dotenv(ENV_PATH)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if OPENAI_API_KEY is None:
    raise ValueError("OPENAI_API_KEY not found in .env file")

judge_client = OpenAI(api_key=OPENAI_API_KEY)


SYSTEM_PROMPT = """
You are an expert linguist and bias detection specialist. Your job is to:
1. Identify ALL biased, loaded, or prejudiced language in the given text.
2. Rewrite the text in a neutral, factual, unbiased way.
3. The "unbiased_text" MUST reproduce the entire original article from beginning to end by replacing only the biased segments with their neutral alternatives. No other content may be removed, added, or omitted.
4. For each biased segment, explain why it is biased and how severe it is.
NOTE: All input articles are known to contain biased or loaded language. Your task is to find and correct them fully.

## Global Severity level
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

## BIAS TYPES TO DETECT
- **Loaded language**: Words that carry strong emotional connotations (e.g. "flooding", "invasion", "destroying")
- **Dehumanizing framing**: Language that strips dignity from groups of people
- **False generalizations**: Sweeping statements about groups ("they always", "all of them")
- **Framing bias**: Selective word choices that imply a particular viewpoint
- **Euphemisms or dysphemisms**: Softening or hardening language to manipulate perception
- **Politically charged terminology**: Labels used to provoke rather than describe
- **Sensationalism**: Exaggerated language to evoke emotional responses

## SEVERITY SCALE
- **high**: Dehumanizing, hateful, or strongly prejudiced language
- **medium**: Framing bias, loaded terms, misleading generalizations
- **low**: Subtle word choice bias, mild framing issues

## SEGMENT RULES
- A segment is a consecutive sequence of words that form a single biased idea
- If two biased words are adjacent and part of the same biased idea, treat them as ONE segment
- If biased words are separated by neutral words, treat them as SEPARATE segments
- The "original" field must be the EXACT substring as it appears in the input text (case-sensitive, no changes)

## UNBIASED TEXT CONSTRUCTION RULES
- The "unbiased_text" must preserve all factual information.
- Preserve all facts while neutralizing all biased language.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- The length of "unbiased_text" must be approximately equal to the length of the input article.
- You must rewrite the full article, not only the sentences containing biased segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

Meaning Preservation Rule (Mandatory)
- The rewritten article must preserve the exact original meaning.
- You MUST NOT change facts, timelines, certainty levels, scope of claims, or the subject of any sentence.
- Do not reverse polarity, generalize specific groups (e.g., “children” → “users”), remove qualifiers (e.g., “reportedly”, “according to”), or introduce new claims.
- If a neutral replacement would alter meaning, do not modify that segment.

Structural Integrity Rule (Mandatory)
- The "unbiased_text" must reproduce the entire original article in the same order and structure, modifying only the identified biased segments.
- Do not remove, add, merge, truncate, duplicate, or reformat content.
- Ensure all replacements are grammatically correct and preserve original punctuation and quotations.

Return ONLY valid JSON following the required schema. No extra text.
""".strip()


BiasType = Literal[
    "loaded language",
    "dehumanizing framing",
    "false generalizations",
    "framing bias",
    "euphemism/dysphemism",
    "politically charged terminology",
    "sensationalism",
]

SegmentSeverity = Literal["high", "medium", "low"]
GlobalSeverity = Literal[2, 3, 4]


class BiasedSegment(BaseModel):
    original: str = Field(..., description="Exact case-sensitive substring from input text")
    replacement: str = Field(..., description="Neutral alternative phrase")
    severity: SegmentSeverity
    bias_type: BiasType
    reasoning: str = Field(..., description="1-2 sentence explanation")


class BiasOutput(BaseModel):
    severity: GlobalSeverity
    biased_segments: List[BiasedSegment]
    unbiased_text: str


def build_prompt(article_text: str) -> str:
    """
    Outlines does not automatically apply chat templates.
    So we embed 'SYSTEM' instructions + the article in one prompt string.
    """
    return f"""SYSTEM:
{SYSTEM_PROMPT}

USER:
Analyze the following article and return JSON only.

ARTICLE:
\"\"\"{article_text}\"\"\"
"""


def truncate_text_to_tokens(tokenizer, text: str, max_tokens: int) -> str:
    """
    Keeps the start of the text if it's too long.
    This prevents context overflow while keeping deterministic behavior.
    """
    ids = tokenizer.encode(text, add_special_tokens=False)
    if len(ids) <= max_tokens:
        return text
    ids = ids[:max_tokens]
    return tokenizer.decode(ids, skip_special_tokens=True)


def post_validate_and_fix(article_text: str, parsed: dict) -> dict:
    """
    Semantic enforcement layer:
    - Drop segments whose `original` is not an exact substring of the input article.
    - Ensure required keys exist (Outlines already guarantees structure, but keep safe).
    """
    segs = parsed.get("biased_segments", [])
    filtered = []
    for seg in segs:
        # seg is a dict after model_dump()
        orig = seg.get("original", "")
        if orig and orig in article_text:  # exact substring check
            filtered.append(seg)

    parsed["biased_segments"] = filtered

    return parsed


def load_outlines_model(model_path: str):
    """
    Returns:
      outlines_model: callable that can do model(prompt, BiasOutput, ...)
      tokenizer: HF tokenizer (for truncation)
    """
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    hf_model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    hf_model.eval()

    outlines_model = outlines.from_transformers(hf_model, tokenizer)
    return outlines_model, tokenizer

def get_token_length(tokenizer, text: str) -> int:
    return len(tokenizer.encode(text, add_special_tokens=False))

def run_inference(outlines_model, tokenizer, article_text: str):

    prompt = build_prompt(article_text)

    input_tokens = len(tokenizer.encode(prompt, add_special_tokens=False))
    model_limit = 32768
    buffer = 500

    max_new = model_limit - input_tokens - buffer

    print(f"\n--- Context Debug ---")
    print(f"Input tokens: {input_tokens}")
    print(f"Available for generation: {model_limit - input_tokens}")
    print(f"Max new tokens allowed: {max_new}")
    print(f"Total possible usage (input + max_new): {input_tokens + max_new}")
    print(f"Model limit: {model_limit}")
    print("----------------------\n")

    if max_new <= 0:
        raise ValueError("Prompt too long for model context window.")

    json_text = outlines_model(
        prompt,
        BiasOutput,
        max_new_tokens=max_new,
    )

    output_tokens = len(tokenizer.encode(json_text, add_special_tokens=False))

    print(f"Generated tokens: {output_tokens}")
    print(f"Final total tokens: {input_tokens + output_tokens}")
    print(f"Headroom left: {model_limit - (input_tokens + output_tokens)}\n")


    if not json_text.strip().endswith("}"):

        print("⚠️ Truncation detected. Retrying with capped generation...")

        # Cap to 2x article size (safe bound)
        article_tokens = len(tokenizer.encode(article_text, add_special_tokens=False))
        capped_max = min(int(article_tokens * 2), 12000)

        print(f"Retrying with capped max_new: {capped_max}")

        
        json_text = outlines_model(
            prompt,
            BiasOutput,
            max_new_tokens=capped_max,
        )
        if not json_text.strip().endswith("}"):
            raise ValueError("Model output still truncated after retry.")


    obj = BiasOutput.model_validate_json(json_text).model_dump()
    obj = post_validate_and_fix(article_text, obj)

    return {
        "binary_label": "biased",
        "bias_found": True,
        "severity": obj["severity"],
        "biased_segments": obj["biased_segments"],
        "unbiased_text": obj["unbiased_text"],
    }


def validate_judge_output(obj):
    if "A" not in obj or "B" not in obj:
        raise ValueError("Judge output missing A or B")

    for key in ["A", "B"]:
        for metric in ["bias", "faithfulness", "fluency"]:
            if metric not in obj[key]:
                raise ValueError(f"Missing {metric} in judge output")
            if not isinstance(obj[key][metric], int):
                raise ValueError(f"{metric} must be integer")
            if not (0 <= obj[key][metric] <= 5):
                raise ValueError(f"{metric} must be 0-5")
    return True


def judge_models(original, rewrite_a, rewrite_b):

    prompt = f"""
You are an expert evaluator of political bias correction in news text.

Your task is to evaluate two rewritten versions of an original article.
The original article is known to be biased. Your goal is to assess how well each rewrite neutralizes the bias while preserving the original meaning.
------------------------------------------
ORIGINAL ARTICLE:
------------------------------------------
{original}

------------------------------------------
REWRITE A:
------------------------------------------
{rewrite_a}

------------------------------------------
REWRITE B:
------------------------------------------
{rewrite_b}

------------------------------------------
EVALUATION INSTRUCTIONS
------------------------------------------

You must evaluate each rewrite independently using the following criteria:

1️. Bias Reduction (0–5)
- 0 = Highly biased language remains
- 1 = Minimal bias reduction
- 2 = Some bias reduced but framing still persuasive
- 3 = Moderately neutral but subtle bias remains
- 4 = Largely neutral with minimal residual framing
- 5 = Fully neutral, factual, and free of emotionally loaded language

Bias includes:
- Loaded language
- Dehumanizing framing
- Exaggeration
- Political persuasion
- Emotionally charged terminology
- Sensational tone

2️. Faithfulness to Original Facts (0–5)
- 0 = Major factual distortions or added information
- 1 = Multiple factual inaccuracies
- 2 = Some meaning distortion
- 3 = Mostly faithful with minor paraphrasing drift
- 4 = Faithful to original facts with neutral wording
- 5 = Completely faithful, no factual changes

Important:
- Do NOT penalize for shortening text.
- Do penalize if new claims are introduced.
- Do penalize if key factual claims are removed.

3️. Fluency & Coherence (0–5)
- 0 = Unreadable or broken grammar
- 1 = Major grammatical issues
- 2 = Understandable but awkward
- 3 = Mostly fluent with minor issues
- 4 = Fluent and well-structured
- 5 = Highly fluent and professional

------------------------------------------
SCORING RULES
------------------------------------------

- Scores must be integers only.
- Scores must be between 0 and 5.
- Evaluate A and B independently.
- Do NOT explain your reasoning.
- Return ONLY valid JSON.
- Do NOT include commentary before or after JSON.

------------------------------------------
OUTPUT FORMAT
------------------------------------------

{{
  "A": {{
    "bias": int,
    "faithfulness": int,
    "fluency": int
  }},
  "B": {{
    "bias": int,
    "faithfulness": int,
    "fluency": int
  }}
}}
"""

    response = judge_client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.choices[0].message.content
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("Judge did not return JSON")

    parsed = json.loads(raw[start:end + 1])
    validate_judge_output(parsed)
    return parsed


def main():
    print("Loading test dataset...")
    df = pd.read_csv(TEST_CSV)

    print("Loading Base model (Outlines)...")
    base_outlines_model, base_tokenizer = load_outlines_model(BASE_MODEL)

    print("Filtering articles with token length <= 5000...")
    
    token_lengths = []
    keep_rows = []

    for i, row in df.iterrows():
        article = row["article_text"]
        token_len = get_token_length(base_tokenizer, article)
        token_lengths.append(token_len)

        if token_len <= MAX_ARTICLE_TOKENS:
            keep_rows.append(True)
        else:
            keep_rows.append(False)

    df["token_length"] = token_lengths
    original_count = len(df)
    df = df[keep_rows].reset_index(drop=True)

    print(f"Original samples: {original_count}")
    print(f"Filtered samples (<= 5000 tokens): {len(df)}")
    print(f"Removed samples: {original_count - len(df)}")


    print("Loading Fine-tuned model (Outlines)...")
    ft_outlines_model, ft_tokenizer = load_outlines_model(FT_MODEL)

    results = []

    for i, row in tqdm(df.iterrows(), total=len(df)):
        print("\n" + "=" * 80)
        print(f"PROCESSING SAMPLE {i + 1}/{len(df)}")
        print("=" * 80)

        article = row["article_text"]

        try:
            print("\n--- ORIGINAL ARTICLE ---")
            print(article)

        
            print("\n--- RUNNING BASE MODEL (Outlines) ---")
            base_output = run_inference(base_outlines_model, base_tokenizer, article)
            print("\nBASE MODEL OUTPUT JSON:")
            print(json.dumps(base_output, indent=2, ensure_ascii=False))

        
            print("\n--- RUNNING FINE-TUNED MODEL (Outlines) ---")
            ft_output = run_inference(ft_outlines_model, ft_tokenizer, article)
            print("\nFINE-TUNED MODEL OUTPUT JSON:")
            print(json.dumps(ft_output, indent=2, ensure_ascii=False))

            print("\n--- RUNNING GPT-4o JUDGE ---")
            scores = judge_models(
                article,
                base_output["unbiased_text"],
                ft_output["unbiased_text"],
            )
            print("\nJUDGE SCORES:")
            print(json.dumps(scores, indent=2))

            results.append({
                "index": i,
                "base_bias": scores["A"]["bias"],
                "base_faithfulness": scores["A"]["faithfulness"],
                "base_fluency": scores["A"]["fluency"],
                "ft_bias": scores["B"]["bias"],
                "ft_faithfulness": scores["B"]["faithfulness"],
                "ft_fluency": scores["B"]["fluency"],
            })

            pd.DataFrame(results).to_csv(OUTPUT_RESULTS, index=False)

        except Exception as e:
            print(f"\n ERROR at index {i}: {e}")
            continue

    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_RESULTS, index=False)

    print("\n" + "=" * 80)
    print("EVALUATION COMPLETE")
    print("=" * 80)

    if len(results_df) == 0:
        print("No successful samples to summarize.")
        return

    print("\nBASE MODEL AVERAGES:")
    print(results_df[["base_bias", "base_faithfulness", "base_fluency"]].mean())

    print("\nFINE-TUNED MODEL AVERAGES:")
    print(results_df[["ft_bias", "ft_faithfulness", "ft_fluency"]].mean())

    results_df["base_total"] = (
        results_df["base_bias"] + results_df["base_faithfulness"] + results_df["base_fluency"]
    )
    results_df["ft_total"] = (
        results_df["ft_bias"] + results_df["ft_faithfulness"] + results_df["ft_fluency"]
    )

    ft_wins = (results_df["ft_total"] > results_df["base_total"]).sum()
    base_wins = (results_df["base_total"] > results_df["ft_total"]).sum()
    ties = (results_df["ft_total"] == results_df["base_total"]).sum()

    print("\nWIN RATE:")
    print(f"FT Wins: {ft_wins}")
    print(f"Base Wins: {base_wins}")
    print(f"Ties: {ties}")
    print("=" * 80)


if __name__ == "__main__":
    main()