import os
import json
import torch
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from transformers import AutoTokenizer, AutoModelForCausalLM
import outlines
from typing import List, Literal
from pydantic import BaseModel, Field

print("Running inference with fine-tuned Qwen2.5-7B model")


FT_MODEL = "/Unbias/Models/Qwen25_Unbias_4k_5epoch"
TEST_CSV = "/Unbias/VLDBench_test_50_biased.csv"

OUTPUT_FILE = "ft_model_inference_resultsfinal.json"

MAX_SEQ_LENGTH = 8192
MAX_ARTICLE_TOKENS = 5000
MAX_NEW_TOKENS = 8000



SYSTEM_PROMPT = """
You are an expert linguist and bias detection specialist. Your job is to:
1. Identify ALL biased, loaded, or prejudiced language in the given text.
2. Rewrite the text in a neutral, factual, unbiased way.
3. The "unbiased_text" MUST reproduce the entire original article from beginning to end by replacing only the biased segments with their neutral alternatives. No other content may be removed, added, or omitted.
4. For each biased segment, explain why it is biased and how severe it is.
NOTE: All input articles are known to contain biased or loaded language. Your task is to find and correct them fully.

## Global Severity level
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

## BIAS TYPES TO DETECT
- **Loaded language**: Words that carry strong emotional connotations (e.g. "flooding", "invasion", "destroying")
- **Dehumanizing framing**: Language that strips dignity from groups of people
- **False generalizations**: Sweeping statements about groups ("they always", "all of them")
- **Framing bias**: Selective word choices that imply a particular viewpoint
- **Euphemisms or dysphemisms**: Softening or hardening language to manipulate perception
- **Politically charged terminology**: Labels used to provoke rather than describe
- **Sensationalism**: Exaggerated language to evoke emotional responses

## SEVERITY SCALE
- **high**: Dehumanizing, hateful, or strongly prejudiced language
- **medium**: Framing bias, loaded terms, misleading generalizations
- **low**: Subtle word choice bias, mild framing issues

## SEGMENT RULES
- A segment is a consecutive sequence of words that form a single biased idea
- If two biased words are adjacent and part of the same biased idea, treat them as ONE segment
- If biased words are separated by neutral words, treat them as SEPARATE segments
- The "original" field must be the EXACT substring as it appears in the input text (case-sensitive, no changes)

## UNBIASED TEXT CONSTRUCTION RULES
- The "unbiased_text" must preserve all factual information.
- Preserve all facts while neutralizing all biased language.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- The length of "unbiased_text" must be approximately equal to the length of the input article.
- You must rewrite the full article, not only the sentences containing biased segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

Return ONLY valid JSON following the required schema. No extra text.
""".strip()


BiasType = Literal[
    "loaded language",
    "dehumanizing framing",
    "false generalizations",
    "framing bias",
    "euphemism/dysphemism",
    "politically charged terminology",
    "sensationalism",
]

SegmentSeverity = Literal["high", "medium", "low"]
GlobalSeverity = Literal[2, 3, 4]


class BiasedSegment(BaseModel):
    original: str = Field(..., description="Exact case-sensitive substring from input text")
    replacement: str = Field(..., description="Neutral alternative phrase")
    severity: SegmentSeverity
    bias_type: BiasType
    reasoning: str = Field(..., description="1-2 sentence explanation")


class BiasOutput(BaseModel):
    severity: GlobalSeverity
    biased_segments: List[BiasedSegment]
    unbiased_text: str

def build_prompt(article_text: str) -> str:
    """
    Outlines does not automatically apply chat templates.
    So we embed 'SYSTEM' instructions + the article in one prompt string.
    """
    return f"""SYSTEM:
{SYSTEM_PROMPT}

USER:
Analyze the following article and return JSON only.

ARTICLE:
\"\"\"{article_text}\"\"\"
"""

def get_token_length(tokenizer, text: str) -> int:
    return len(tokenizer.encode(text, add_special_tokens=False))


def post_validate(article_text: str, parsed: dict) -> dict:
    """
    Ensure segments exist in original article.
    """
    filtered = []
    for seg in parsed.get("biased_segments", []):
        if seg["original"] in article_text:
            filtered.append(seg)

    parsed["biased_segments"] = filtered
    return parsed


def load_model(model_path: str):
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    model.eval()

    outlines_model = outlines.from_transformers(model, tokenizer)
    return outlines_model, tokenizer

def run_inference(outlines_model, tokenizer, article_text: str):

    prompt = build_prompt(article_text)

    input_tokens = len(tokenizer.encode(prompt, add_special_tokens=False))
    model_limit = 32768
    buffer = 500

    max_new = model_limit - input_tokens - buffer

    print(f"\n--- Context Debug ---")
    print(f"Input tokens: {input_tokens}")
    print(f"Available for generation: {model_limit - input_tokens}")
    print(f"Max new tokens allowed: {max_new}")
    print(f"Total possible usage (input + max_new): {input_tokens + max_new}")
    print(f"Model limit: {model_limit}")
    print("----------------------\n")

    if max_new <= 0:
        raise ValueError("Prompt too long for model context window.")

    json_text = outlines_model(
        prompt,
        BiasOutput,
        max_new_tokens=max_new,
    )

    output_tokens = len(tokenizer.encode(json_text, add_special_tokens=False))

    print(f"Generated tokens: {output_tokens}")
    print(f"Final total tokens: {input_tokens + output_tokens}")
    print(f"Headroom left: {model_limit - (input_tokens + output_tokens)}\n")


    if not json_text.strip().endswith("}"):

        print("⚠️ Truncation detected. Retrying with capped generation...")

    
        article_tokens = len(tokenizer.encode(article_text, add_special_tokens=False))
        capped_max = min(int(article_tokens * 2), 12000)

        print(f"Retrying with capped max_new: {capped_max}")

        json_text = outlines_model(
            prompt,
            BiasOutput,
            max_new_tokens=capped_max,
        )

        if not json_text.strip().endswith("}"):
            raise ValueError("Model output still truncated after retry.")


    obj = BiasOutput.model_validate_json(json_text).model_dump()
    obj = post_validate(article_text, obj)

    return {
        "binary_label": "biased",
        "bias_found": True,
        "severity": obj["severity"],
        "biased_segments": obj["biased_segments"],
        "unbiased_text": obj["unbiased_text"],
    }

def main():
    print("Loading dataset...")
    df = pd.read_csv(TEST_CSV)

    print("Loading fine-tuned model...")
    outlines_model, tokenizer = load_model(FT_MODEL)

    print("Filtering articles <= 5000 tokens...")

    token_lengths = []
    keep_mask = []

    for _, row in df.iterrows():
        article = row["article_text"]
        length = get_token_length(tokenizer, article)
        token_lengths.append(length)
        keep_mask.append(length <= MAX_ARTICLE_TOKENS)

    df["token_length"] = token_lengths
    df = df[keep_mask].reset_index(drop=True)

    print(f"Final sample count: {len(df)}")

    results = []

    for i, row in tqdm(df.iterrows(), total=len(df)):
        print("\n" + "=" * 80)
        print(f"Processing sample {i+1}/{len(df)}")
        print("=" * 80)

        article = row["article_text"]

        try:
            output = run_inference(outlines_model, tokenizer, article)

            results.append({
                "index": i,
                "token_length": row["token_length"],
                "output": output
            })

            with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
                json.dump(results, f, indent=2, ensure_ascii=False)

        except Exception as e:
            print(f"Error at index {i}: {e}")
            continue

    print("\nInference complete.")
    print(f"Saved results to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()