"""Run inference with a fine-tuned Qwen2.5-7B model and save structured outputs.

This script:
- Loads a fine-tuned model wrapped with Outlines for schema-constrained JSON output.
- Filters test articles by token length.
- Runs inference with dynamic token budgeting (avoids context overflow).
- Writes results incrementally to a JSON file.

No heavyweight work executes at import time (pre-commit/doctest friendly).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Dict, List, Literal, Tuple

import outlines
import pandas as pd
import torch
from pydantic import BaseModel, Field
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer


FT_MODEL = "/Unbias/Models/Qwen25_Unbias_4k_5epoch"
TEST_CSV = "/Unbias/VLDBench_test_50_biased.csv"

OUTPUT_FILE = "ft_model_inference_resultsfinal.json"

MAX_SEQ_LENGTH = 8192
MAX_ARTICLE_TOKENS = 5000

MODEL_LIMIT = 32768
TOKEN_BUFFER = 500
HARD_MAX_NEW_CAP = 15000
TRUNCATION_RETRY_CAP = 12000

PRINT_CONTEXT_DEBUG = True

SYSTEM_PROMPT = """
You are an expert linguist and bias detection specialist. Your job is to:
1. Identify ALL biased, loaded, or prejudiced language in the given text.
2. Rewrite the text in a neutral, factual, unbiased way.
3. The "unbiased_text" MUST reproduce the entire original article from beginning to end by replacing only the biased segments with their neutral alternatives. No other content may be removed, added, or omitted.
4. For each biased segment, explain why it is biased and how severe it is.
NOTE: All input articles are known to contain biased or loaded language. Your task is to find and correct them fully.

## Global Severity level
2 = recurring biased framing
3 = strong persuasive tone
4 = inflammatory rhetoric

## BIAS TYPES TO DETECT
- **Loaded language**: Words that carry strong emotional connotations (e.g. "flooding", "invasion", "destroying")
- **Dehumanizing framing**: Language that strips dignity from groups of people
- **False generalizations**: Sweeping statements about groups ("they always", "all of them")
- **Framing bias**: Selective word choices that imply a particular viewpoint
- **Euphemisms or dysphemisms**: Softening or hardening language to manipulate perception
- **Politically charged terminology**: Labels used to provoke rather than describe
- **Sensationalism**: Exaggerated language to evoke emotional responses

## SEVERITY SCALE
- **high**: Dehumanizing, hateful, or strongly prejudiced language
- **medium**: Framing bias, loaded terms, misleading generalizations
- **low**: Subtle word choice bias, mild framing issues

## SEGMENT RULES
- A segment is a consecutive sequence of words that form a single biased idea
- If two biased words are adjacent and part of the same biased idea, treat them as ONE segment
- If biased words are separated by neutral words, treat them as SEPARATE segments
- The "original" field must be the EXACT substring as it appears in the input text (case-sensitive, no changes)

## UNBIASED TEXT CONSTRUCTION RULES
- The "unbiased_text" must preserve all factual information.
- Preserve all facts while neutralizing all biased language.
- It should primarily be generated by applying the proposed replacement phrases.
- Do NOT remove factual content.
- Do NOT add new information.
- Only modify language that appears in biased_segments.
- The length of "unbiased_text" must be approximately equal to the length of the input article.
- You must rewrite the full article, not only the sentences containing biased segments.
- Maintain original sentence structure as much as possible.
- Make sure the sentence is meaningful.

Return ONLY valid JSON following the required schema. No extra text.
""".strip()


BiasType = Literal[
    "loaded language",
    "dehumanizing framing",
    "false generalizations",
    "framing bias",
    "euphemism/dysphemism",
    "politically charged terminology",
    "sensationalism",
]

SegmentSeverity = Literal["high", "medium", "low"]
GlobalSeverity = Literal[2, 3, 4]


class BiasedSegment(BaseModel):
    """Represent a single biased segment found in the article."""

    original: str = Field(
        ..., description="Exact case-sensitive substring from input text"
    )
    replacement: str = Field(..., description="Neutral alternative phrase")
    severity: SegmentSeverity
    bias_type: BiasType
    reasoning: str = Field(..., description="1-2 sentence explanation")


class BiasOutput(BaseModel):
    """Represent structured bias detection output with a full neutral rewrite."""

    severity: GlobalSeverity
    biased_segments: List[BiasedSegment]
    unbiased_text: str


@dataclass(frozen=True)
class InferenceOutput:
    """Store normalized output for saving to disk."""

    binary_label: str
    bias_found: bool
    severity: int
    biased_segments: List[Dict[str, Any]]
    unbiased_text: str


def build_prompt(article_text: str) -> str:
    """Build a single prompt string embedding system instructions and the article."""
    return f"""SYSTEM:
{SYSTEM_PROMPT}

USER:
Analyze the following article and return JSON only.

ARTICLE:
\"\"\"{article_text}\"\"\"
"""


def get_token_length(tokenizer: Any, text: str) -> int:
    """Return token length of text using the provided tokenizer."""
    return len(tokenizer.encode(text, add_special_tokens=False))


def post_validate(article_text: str, parsed: Dict[str, Any]) -> Dict[str, Any]:
    """Filter segments whose `original` is not an exact substring of the article."""
    filtered: List[Dict[str, Any]] = []
    for seg in parsed.get("biased_segments", []):
        orig = seg.get("original")
        if isinstance(orig, str) and orig and orig in article_text:
            filtered.append(seg)

    parsed["biased_segments"] = filtered
    return parsed


def compute_max_new_tokens(tokenizer: Any, prompt: str) -> int:
    """Compute a safe generation budget based on prompt token length."""
    input_tokens = len(tokenizer.encode(prompt, add_special_tokens=False))
    available = MODEL_LIMIT - input_tokens - TOKEN_BUFFER
    if available <= 0:
        raise ValueError("Prompt too long for model context window.")
    return min(HARD_MAX_NEW_CAP, available)


def load_model(model_path: str) -> Tuple[Any, Any]:
    """Load a CausalLM and wrap it with Outlines."""
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    model.eval()

    outlines_model = outlines.from_transformers(model, tokenizer)
    return outlines_model, tokenizer


def _print_context_debug(tokenizer: Any, prompt: str, json_text: str) -> None:
    """Print token usage diagnostics for debugging context limits."""
    input_tokens = len(tokenizer.encode(prompt, add_special_tokens=False))
    output_tokens = len(tokenizer.encode(json_text, add_special_tokens=False))
    total = input_tokens + output_tokens

    print("\n--- Context Debug ---")
    print(f"Input tokens: {input_tokens}")
    print(f"Output tokens: {output_tokens}")
    print(f"Total tokens: {total}")
    print(f"Model limit: {MODEL_LIMIT}")
    print(f"Headroom left: {MODEL_LIMIT - total}")
    print("----------------------\n")


def run_inference(
    outlines_model: Any, tokenizer: Any, article_text: str
) -> InferenceOutput:
    """Run schema-constrained inference with dynamic token budgeting and validation."""
    prompt = build_prompt(article_text)

    max_new = compute_max_new_tokens(tokenizer, prompt)

    json_text = outlines_model(
        prompt,
        BiasOutput,
        max_new_tokens=max_new,
    )

    if PRINT_CONTEXT_DEBUG:
        _print_context_debug(tokenizer, prompt, json_text)

    if not json_text.strip().endswith("}"):
        article_tokens = len(tokenizer.encode(article_text, add_special_tokens=False))
        capped_max = min(int(article_tokens * 2), TRUNCATION_RETRY_CAP)

        json_text = outlines_model(
            prompt,
            BiasOutput,
            max_new_tokens=capped_max,
        )

        if not json_text.strip().endswith("}"):
            raise ValueError("Model output still truncated after retry.")

    obj = BiasOutput.model_validate_json(json_text).model_dump()
    obj = post_validate(article_text, obj)

    return InferenceOutput(
        binary_label="biased",
        bias_found=True,
        severity=int(obj["severity"]),
        biased_segments=list(obj["biased_segments"]),
        unbiased_text=str(obj["unbiased_text"]),
    )


def filter_articles(
    df: pd.DataFrame, tokenizer: Any, max_article_tokens: int
) -> pd.DataFrame:
    """Filter DataFrame to articles with token length below a threshold."""
    token_lengths: List[int] = []
    keep_mask: List[bool] = []

    for _, row in df.iterrows():
        article = row["article_text"]
        length = get_token_length(tokenizer, article)
        token_lengths.append(length)
        keep_mask.append(length <= max_article_tokens)

    out = df.copy()
    out["token_length"] = token_lengths
    return out[keep_mask].reset_index(drop=True)


def save_results(results: List[Dict[str, Any]], path: str) -> None:
    """Write inference results to a JSON file."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)


def main() -> None:
    """Run inference over the test CSV and save outputs to a JSON file."""
    print("Running inference with fine-tuned Qwen2.5-7B model")

    print("Loading dataset...")
    df = pd.read_csv(TEST_CSV)

    print("Loading fine-tuned model...")
    outlines_model, tokenizer = load_model(FT_MODEL)

    print(f"Filtering articles <= {MAX_ARTICLE_TOKENS} tokens...")
    df = filter_articles(df, tokenizer, MAX_ARTICLE_TOKENS)
    print(f"Final sample count: {len(df)}")

    results: List[Dict[str, Any]] = []

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        article = row["article_text"]

        try:
            out = run_inference(outlines_model, tokenizer, article)

            results.append(
                {
                    "index": int(idx),
                    "token_length": int(row["token_length"]),
                    "output": {
                        "binary_label": out.binary_label,
                        "bias_found": out.bias_found,
                        "severity": out.severity,
                        "biased_segments": out.biased_segments,
                        "unbiased_text": out.unbiased_text,
                    },
                }
            )

            save_results(results, OUTPUT_FILE)
        except Exception as exc:
            print(f"Error at index {idx}: {exc}")
            continue

    print("\nInference complete.")
    print(f"Saved results to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
